
laodobj:
	 g++ loadobj_test.cc \
		 -I ~/.xmake/packages/t/tinyobjloader/v2.0.0rc10/9ba365241ff049719bcece05457e50f4/include/ \
		 -l tinyobjloader \
		 -L ~/.xmake/packages/t/tinyobjloader/v2.0.0rc10/9ba365241ff049719bcece05457e50f4/lib/
