


test:
	@echo "Test contracts..."
	npx hardhat test
	@#npx hardhat test --network 


verify_token:
	npx hardhat verify --contract contracts/Token.sol:Token --network sepolia 0xcf3BE48bBFEc22Ea2a126E16408C5D8acC36D96B